### ISSUE TITLE
Error analystty.py: DIRECTORY_ENTRY_IMPORT

### ISSUE THREAD

**Issue by desmonHak** [tty503/analystty#1]
```py
C:\Users\desmon0xff\Desktop\analystty\src>python __init__.py
Traceback (most recent call last):
  File "C:\Users\desmon0xff\Desktop\analystty\src\__init__.py", line 65, in <module>
    obj   = analystty.frm_pe(pe)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\desmon0xff\Desktop\analystty\src\analystty.py", line 36, in __init__
    self.__getImports()
  File "C:\Users\desmon0xff\Desktop\analystty\src\analystty.py", line 53, in __getImports
    for entry in self.__pe.DIRECTORY_ENTRY_IMPORT:
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PE' object has no attribute 'DIRECTORY_ENTRY_IMPORT'. Did you mean: 'DIRECTORY_ENTRY_BASERELOC'?
```

**Comment by tty503** [comment]
Al parecer es algún problema con las dependencias de los módulos, reitero mis disculpa por la inexperiencia en dejar el venv en lugar de armar un setup con su respectivo requeriments.txt. En seguida trabajaré en ello.

**Comment by desmonHak** [comment]
Animo bro, te animo a seguir con el proyecto
